"""followers

Revision ID: 1cbe1cdc746f
Revises: 7058462ea17d
Create Date: 2025-12-29 15:44:13.077843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cbe1cdc746f'
down_revision = '7058462ea17d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower', sa.String(length=64), nullable=False),
    sa.Column('followed', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['followed'], ['user.username'], ),
    sa.ForeignKeyConstraint(['follower'], ['user.username'], ),
    sa.PrimaryKeyConstraint('follower', 'followed')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
